package liv.ac.uk.live_in.dao;

import java.util.Date;

/**
 * accommodationdao object
 * 
 **/
public class Accommodation {
    /**
     *
     */
    private Integer id;

    /** Accommodation name */
    private String acmdName;

    /** Geography longitude */
    private String longitude;

    /** Geography Latitude */
    private String latitude;

    /** Nearby facility map url list */
    private String facilities;

    /** Official website link */
    private String webUrl;

    /**  */
    private String picUrl;

    /** flat amenities list */
    private String amenities;

    /**  */
    private Date createdDate;

    /**  */
    private Date modifiedDate;

    /** Distance to north campus */
    private String distanceToNorth;

    /** Distance to south campus */
    private String distanceToSouth;

    /** Average rating */
    private Double ratings;

    /**  */
    private String postcode;

    /**  */
    private Double distanceToCampus;

    /**  */
    private Boolean deleteStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accommodation.id
     *
     * @return the value of accommodation.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accommodation.id
     *
     * @param id the value for accommodation.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accommodation.acmd_name
     *
     * @return the value of accommodation.acmd_name
     *
     * @mbggenerated
     */
    public String getAcmdName() {
        return acmdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accommodation.acmd_name
     *
     * @param acmdName the value for accommodation.acmd_name
     *
     * @mbggenerated
     */
    public void setAcmdName(String acmdName) {
        this.acmdName = acmdName == null ? null : acmdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accommodation.longitude
     *
     * @return the value of accommodation.longitude
     *
     * @mbggenerated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accommodation.longitude
     *
     * @param longitude the value for accommodation.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accommodation.latitude
     *
     * @return the value of accommodation.latitude
     *
     * @mbggenerated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accommodation.latitude
     *
     * @param latitude the value for accommodation.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accommodation.facilities
     *
     * @return the value of accommodation.facilities
     *
     * @mbggenerated
     */
    public String getFacilities() {
        return facilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accommodation.facilities
     *
     * @param facilities the value for accommodation.facilities
     *
     * @mbggenerated
     */
    public void setFacilities(String facilities) {
        this.facilities = facilities == null ? null : facilities.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accommodation.web_url
     *
     * @return the value of accommodation.web_url
     *
     * @mbggenerated
     */
    public String getWebUrl() {
        return webUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accommodation.web_url
     *
     * @param webUrl the value for accommodation.web_url
     *
     * @mbggenerated
     */
    public void setWebUrl(String webUrl) {
        this.webUrl = webUrl == null ? null : webUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accommodation.pic_url
     *
     * @return the value of accommodation.pic_url
     *
     * @mbggenerated
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accommodation.pic_url
     *
     * @param picUrl the value for accommodation.pic_url
     *
     * @mbggenerated
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accommodation.amenities
     *
     * @return the value of accommodation.amenities
     *
     * @mbggenerated
     */
    public String getAmenities() {
        return amenities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accommodation.amenities
     *
     * @param amenities the value for accommodation.amenities
     *
     * @mbggenerated
     */
    public void setAmenities(String amenities) {
        this.amenities = amenities == null ? null : amenities.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accommodation.created_date
     *
     * @return the value of accommodation.created_date
     *
     * @mbggenerated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accommodation.created_date
     *
     * @param createdDate the value for accommodation.created_date
     *
     * @mbggenerated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accommodation.modified_date
     *
     * @return the value of accommodation.modified_date
     *
     * @mbggenerated
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accommodation.modified_date
     *
     * @param modifiedDate the value for accommodation.modified_date
     *
     * @mbggenerated
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accommodation.distance_to_north
     *
     * @return the value of accommodation.distance_to_north
     *
     * @mbggenerated
     */
    public String getDistanceToNorth() {
        return distanceToNorth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accommodation.distance_to_north
     *
     * @param distanceToNorth the value for accommodation.distance_to_north
     *
     * @mbggenerated
     */
    public void setDistanceToNorth(String distanceToNorth) {
        this.distanceToNorth = distanceToNorth == null ? null : distanceToNorth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accommodation.distance_to_south
     *
     * @return the value of accommodation.distance_to_south
     *
     * @mbggenerated
     */
    public String getDistanceToSouth() {
        return distanceToSouth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accommodation.distance_to_south
     *
     * @param distanceToSouth the value for accommodation.distance_to_south
     *
     * @mbggenerated
     */
    public void setDistanceToSouth(String distanceToSouth) {
        this.distanceToSouth = distanceToSouth == null ? null : distanceToSouth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accommodation.ratings
     *
     * @return the value of accommodation.ratings
     *
     * @mbggenerated
     */
    public Double getRatings() {
        return ratings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accommodation.ratings
     *
     * @param ratings the value for accommodation.ratings
     *
     * @mbggenerated
     */
    public void setRatings(Double ratings) {
        this.ratings = ratings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accommodation.postcode
     *
     * @return the value of accommodation.postcode
     *
     * @mbggenerated
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accommodation.postcode
     *
     * @param postcode the value for accommodation.postcode
     *
     * @mbggenerated
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accommodation.distance_to_campus
     *
     * @return the value of accommodation.distance_to_campus
     *
     * @mbggenerated
     */
    public Double getDistanceToCampus() {
        return distanceToCampus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accommodation.distance_to_campus
     *
     * @param distanceToCampus the value for accommodation.distance_to_campus
     *
     * @mbggenerated
     */
    public void setDistanceToCampus(Double distanceToCampus) {
        this.distanceToCampus = distanceToCampus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accommodation.delete_status
     *
     * @return the value of accommodation.delete_status
     *
     * @mbggenerated
     */
    public Boolean getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accommodation.delete_status
     *
     * @param deleteStatus the value for accommodation.delete_status
     *
     * @mbggenerated
     */
    public void setDeleteStatus(Boolean deleteStatus) {
        this.deleteStatus = deleteStatus;
    }
}