package liv.ac.uk.live_in.dao;

import liv.ac.uk.live_in.page.Page;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AccommodationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    protected Page page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    public AccommodationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    public void setPage(Page page) {
        this.page=page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    public Page getPage() {
        return page;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAcmdNameIsNull() {
            addCriterion("acmd_name is null");
            return (Criteria) this;
        }

        public Criteria andAcmdNameIsNotNull() {
            addCriterion("acmd_name is not null");
            return (Criteria) this;
        }

        public Criteria andAcmdNameEqualTo(String value) {
            addCriterion("acmd_name =", value, "acmdName");
            return (Criteria) this;
        }

        public Criteria andAcmdNameNotEqualTo(String value) {
            addCriterion("acmd_name <>", value, "acmdName");
            return (Criteria) this;
        }

        public Criteria andAcmdNameGreaterThan(String value) {
            addCriterion("acmd_name >", value, "acmdName");
            return (Criteria) this;
        }

        public Criteria andAcmdNameGreaterThanOrEqualTo(String value) {
            addCriterion("acmd_name >=", value, "acmdName");
            return (Criteria) this;
        }

        public Criteria andAcmdNameLessThan(String value) {
            addCriterion("acmd_name <", value, "acmdName");
            return (Criteria) this;
        }

        public Criteria andAcmdNameLessThanOrEqualTo(String value) {
            addCriterion("acmd_name <=", value, "acmdName");
            return (Criteria) this;
        }

        public Criteria andAcmdNameLike(String value) {
            addCriterion("acmd_name like", value, "acmdName");
            return (Criteria) this;
        }

        public Criteria andAcmdNameNotLike(String value) {
            addCriterion("acmd_name not like", value, "acmdName");
            return (Criteria) this;
        }

        public Criteria andAcmdNameIn(List<String> values) {
            addCriterion("acmd_name in", values, "acmdName");
            return (Criteria) this;
        }

        public Criteria andAcmdNameNotIn(List<String> values) {
            addCriterion("acmd_name not in", values, "acmdName");
            return (Criteria) this;
        }

        public Criteria andAcmdNameBetween(String value1, String value2) {
            addCriterion("acmd_name between", value1, value2, "acmdName");
            return (Criteria) this;
        }

        public Criteria andAcmdNameNotBetween(String value1, String value2) {
            addCriterion("acmd_name not between", value1, value2, "acmdName");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNull() {
            addCriterion("longitude is null");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNotNull() {
            addCriterion("longitude is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudeEqualTo(String value) {
            addCriterion("longitude =", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotEqualTo(String value) {
            addCriterion("longitude <>", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThan(String value) {
            addCriterion("longitude >", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThanOrEqualTo(String value) {
            addCriterion("longitude >=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThan(String value) {
            addCriterion("longitude <", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThanOrEqualTo(String value) {
            addCriterion("longitude <=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLike(String value) {
            addCriterion("longitude like", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotLike(String value) {
            addCriterion("longitude not like", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIn(List<String> values) {
            addCriterion("longitude in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotIn(List<String> values) {
            addCriterion("longitude not in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeBetween(String value1, String value2) {
            addCriterion("longitude between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotBetween(String value1, String value2) {
            addCriterion("longitude not between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNull() {
            addCriterion("latitude is null");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNotNull() {
            addCriterion("latitude is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudeEqualTo(String value) {
            addCriterion("latitude =", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotEqualTo(String value) {
            addCriterion("latitude <>", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThan(String value) {
            addCriterion("latitude >", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThanOrEqualTo(String value) {
            addCriterion("latitude >=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThan(String value) {
            addCriterion("latitude <", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThanOrEqualTo(String value) {
            addCriterion("latitude <=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLike(String value) {
            addCriterion("latitude like", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotLike(String value) {
            addCriterion("latitude not like", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIn(List<String> values) {
            addCriterion("latitude in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotIn(List<String> values) {
            addCriterion("latitude not in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeBetween(String value1, String value2) {
            addCriterion("latitude between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotBetween(String value1, String value2) {
            addCriterion("latitude not between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andFacilitiesIsNull() {
            addCriterion("facilities is null");
            return (Criteria) this;
        }

        public Criteria andFacilitiesIsNotNull() {
            addCriterion("facilities is not null");
            return (Criteria) this;
        }

        public Criteria andFacilitiesEqualTo(String value) {
            addCriterion("facilities =", value, "facilities");
            return (Criteria) this;
        }

        public Criteria andFacilitiesNotEqualTo(String value) {
            addCriterion("facilities <>", value, "facilities");
            return (Criteria) this;
        }

        public Criteria andFacilitiesGreaterThan(String value) {
            addCriterion("facilities >", value, "facilities");
            return (Criteria) this;
        }

        public Criteria andFacilitiesGreaterThanOrEqualTo(String value) {
            addCriterion("facilities >=", value, "facilities");
            return (Criteria) this;
        }

        public Criteria andFacilitiesLessThan(String value) {
            addCriterion("facilities <", value, "facilities");
            return (Criteria) this;
        }

        public Criteria andFacilitiesLessThanOrEqualTo(String value) {
            addCriterion("facilities <=", value, "facilities");
            return (Criteria) this;
        }

        public Criteria andFacilitiesLike(String value) {
            addCriterion("facilities like", value, "facilities");
            return (Criteria) this;
        }

        public Criteria andFacilitiesNotLike(String value) {
            addCriterion("facilities not like", value, "facilities");
            return (Criteria) this;
        }

        public Criteria andFacilitiesIn(List<String> values) {
            addCriterion("facilities in", values, "facilities");
            return (Criteria) this;
        }

        public Criteria andFacilitiesNotIn(List<String> values) {
            addCriterion("facilities not in", values, "facilities");
            return (Criteria) this;
        }

        public Criteria andFacilitiesBetween(String value1, String value2) {
            addCriterion("facilities between", value1, value2, "facilities");
            return (Criteria) this;
        }

        public Criteria andFacilitiesNotBetween(String value1, String value2) {
            addCriterion("facilities not between", value1, value2, "facilities");
            return (Criteria) this;
        }

        public Criteria andWebUrlIsNull() {
            addCriterion("web_url is null");
            return (Criteria) this;
        }

        public Criteria andWebUrlIsNotNull() {
            addCriterion("web_url is not null");
            return (Criteria) this;
        }

        public Criteria andWebUrlEqualTo(String value) {
            addCriterion("web_url =", value, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlNotEqualTo(String value) {
            addCriterion("web_url <>", value, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlGreaterThan(String value) {
            addCriterion("web_url >", value, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlGreaterThanOrEqualTo(String value) {
            addCriterion("web_url >=", value, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlLessThan(String value) {
            addCriterion("web_url <", value, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlLessThanOrEqualTo(String value) {
            addCriterion("web_url <=", value, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlLike(String value) {
            addCriterion("web_url like", value, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlNotLike(String value) {
            addCriterion("web_url not like", value, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlIn(List<String> values) {
            addCriterion("web_url in", values, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlNotIn(List<String> values) {
            addCriterion("web_url not in", values, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlBetween(String value1, String value2) {
            addCriterion("web_url between", value1, value2, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlNotBetween(String value1, String value2) {
            addCriterion("web_url not between", value1, value2, "webUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlIsNull() {
            addCriterion("pic_url is null");
            return (Criteria) this;
        }

        public Criteria andPicUrlIsNotNull() {
            addCriterion("pic_url is not null");
            return (Criteria) this;
        }

        public Criteria andPicUrlEqualTo(String value) {
            addCriterion("pic_url =", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlNotEqualTo(String value) {
            addCriterion("pic_url <>", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlGreaterThan(String value) {
            addCriterion("pic_url >", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlGreaterThanOrEqualTo(String value) {
            addCriterion("pic_url >=", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlLessThan(String value) {
            addCriterion("pic_url <", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlLessThanOrEqualTo(String value) {
            addCriterion("pic_url <=", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlLike(String value) {
            addCriterion("pic_url like", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlNotLike(String value) {
            addCriterion("pic_url not like", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlIn(List<String> values) {
            addCriterion("pic_url in", values, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlNotIn(List<String> values) {
            addCriterion("pic_url not in", values, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlBetween(String value1, String value2) {
            addCriterion("pic_url between", value1, value2, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlNotBetween(String value1, String value2) {
            addCriterion("pic_url not between", value1, value2, "picUrl");
            return (Criteria) this;
        }

        public Criteria andAmenitiesIsNull() {
            addCriterion("amenities is null");
            return (Criteria) this;
        }

        public Criteria andAmenitiesIsNotNull() {
            addCriterion("amenities is not null");
            return (Criteria) this;
        }

        public Criteria andAmenitiesEqualTo(String value) {
            addCriterion("amenities =", value, "amenities");
            return (Criteria) this;
        }

        public Criteria andAmenitiesNotEqualTo(String value) {
            addCriterion("amenities <>", value, "amenities");
            return (Criteria) this;
        }

        public Criteria andAmenitiesGreaterThan(String value) {
            addCriterion("amenities >", value, "amenities");
            return (Criteria) this;
        }

        public Criteria andAmenitiesGreaterThanOrEqualTo(String value) {
            addCriterion("amenities >=", value, "amenities");
            return (Criteria) this;
        }

        public Criteria andAmenitiesLessThan(String value) {
            addCriterion("amenities <", value, "amenities");
            return (Criteria) this;
        }

        public Criteria andAmenitiesLessThanOrEqualTo(String value) {
            addCriterion("amenities <=", value, "amenities");
            return (Criteria) this;
        }

        public Criteria andAmenitiesLike(String value) {
            addCriterion("amenities like", value, "amenities");
            return (Criteria) this;
        }

        public Criteria andAmenitiesNotLike(String value) {
            addCriterion("amenities not like", value, "amenities");
            return (Criteria) this;
        }

        public Criteria andAmenitiesIn(List<String> values) {
            addCriterion("amenities in", values, "amenities");
            return (Criteria) this;
        }

        public Criteria andAmenitiesNotIn(List<String> values) {
            addCriterion("amenities not in", values, "amenities");
            return (Criteria) this;
        }

        public Criteria andAmenitiesBetween(String value1, String value2) {
            addCriterion("amenities between", value1, value2, "amenities");
            return (Criteria) this;
        }

        public Criteria andAmenitiesNotBetween(String value1, String value2) {
            addCriterion("amenities not between", value1, value2, "amenities");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("created_date is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("created_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(Date value) {
            addCriterion("created_date =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(Date value) {
            addCriterion("created_date <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(Date value) {
            addCriterion("created_date >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("created_date >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(Date value) {
            addCriterion("created_date <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
            addCriterion("created_date <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<Date> values) {
            addCriterion("created_date in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<Date> values) {
            addCriterion("created_date not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(Date value1, Date value2) {
            addCriterion("created_date between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
            addCriterion("created_date not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateIsNull() {
            addCriterion("modified_date is null");
            return (Criteria) this;
        }

        public Criteria andModifiedDateIsNotNull() {
            addCriterion("modified_date is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedDateEqualTo(Date value) {
            addCriterion("modified_date =", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateNotEqualTo(Date value) {
            addCriterion("modified_date <>", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateGreaterThan(Date value) {
            addCriterion("modified_date >", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("modified_date >=", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateLessThan(Date value) {
            addCriterion("modified_date <", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateLessThanOrEqualTo(Date value) {
            addCriterion("modified_date <=", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateIn(List<Date> values) {
            addCriterion("modified_date in", values, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateNotIn(List<Date> values) {
            addCriterion("modified_date not in", values, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateBetween(Date value1, Date value2) {
            addCriterion("modified_date between", value1, value2, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateNotBetween(Date value1, Date value2) {
            addCriterion("modified_date not between", value1, value2, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andDistanceToNorthIsNull() {
            addCriterion("distance_to_north is null");
            return (Criteria) this;
        }

        public Criteria andDistanceToNorthIsNotNull() {
            addCriterion("distance_to_north is not null");
            return (Criteria) this;
        }

        public Criteria andDistanceToNorthEqualTo(String value) {
            addCriterion("distance_to_north =", value, "distanceToNorth");
            return (Criteria) this;
        }

        public Criteria andDistanceToNorthNotEqualTo(String value) {
            addCriterion("distance_to_north <>", value, "distanceToNorth");
            return (Criteria) this;
        }

        public Criteria andDistanceToNorthGreaterThan(String value) {
            addCriterion("distance_to_north >", value, "distanceToNorth");
            return (Criteria) this;
        }

        public Criteria andDistanceToNorthGreaterThanOrEqualTo(String value) {
            addCriterion("distance_to_north >=", value, "distanceToNorth");
            return (Criteria) this;
        }

        public Criteria andDistanceToNorthLessThan(String value) {
            addCriterion("distance_to_north <", value, "distanceToNorth");
            return (Criteria) this;
        }

        public Criteria andDistanceToNorthLessThanOrEqualTo(String value) {
            addCriterion("distance_to_north <=", value, "distanceToNorth");
            return (Criteria) this;
        }

        public Criteria andDistanceToNorthLike(String value) {
            addCriterion("distance_to_north like", value, "distanceToNorth");
            return (Criteria) this;
        }

        public Criteria andDistanceToNorthNotLike(String value) {
            addCriterion("distance_to_north not like", value, "distanceToNorth");
            return (Criteria) this;
        }

        public Criteria andDistanceToNorthIn(List<String> values) {
            addCriterion("distance_to_north in", values, "distanceToNorth");
            return (Criteria) this;
        }

        public Criteria andDistanceToNorthNotIn(List<String> values) {
            addCriterion("distance_to_north not in", values, "distanceToNorth");
            return (Criteria) this;
        }

        public Criteria andDistanceToNorthBetween(String value1, String value2) {
            addCriterion("distance_to_north between", value1, value2, "distanceToNorth");
            return (Criteria) this;
        }

        public Criteria andDistanceToNorthNotBetween(String value1, String value2) {
            addCriterion("distance_to_north not between", value1, value2, "distanceToNorth");
            return (Criteria) this;
        }

        public Criteria andDistanceToSouthIsNull() {
            addCriterion("distance_to_south is null");
            return (Criteria) this;
        }

        public Criteria andDistanceToSouthIsNotNull() {
            addCriterion("distance_to_south is not null");
            return (Criteria) this;
        }

        public Criteria andDistanceToSouthEqualTo(String value) {
            addCriterion("distance_to_south =", value, "distanceToSouth");
            return (Criteria) this;
        }

        public Criteria andDistanceToSouthNotEqualTo(String value) {
            addCriterion("distance_to_south <>", value, "distanceToSouth");
            return (Criteria) this;
        }

        public Criteria andDistanceToSouthGreaterThan(String value) {
            addCriterion("distance_to_south >", value, "distanceToSouth");
            return (Criteria) this;
        }

        public Criteria andDistanceToSouthGreaterThanOrEqualTo(String value) {
            addCriterion("distance_to_south >=", value, "distanceToSouth");
            return (Criteria) this;
        }

        public Criteria andDistanceToSouthLessThan(String value) {
            addCriterion("distance_to_south <", value, "distanceToSouth");
            return (Criteria) this;
        }

        public Criteria andDistanceToSouthLessThanOrEqualTo(String value) {
            addCriterion("distance_to_south <=", value, "distanceToSouth");
            return (Criteria) this;
        }

        public Criteria andDistanceToSouthLike(String value) {
            addCriterion("distance_to_south like", value, "distanceToSouth");
            return (Criteria) this;
        }

        public Criteria andDistanceToSouthNotLike(String value) {
            addCriterion("distance_to_south not like", value, "distanceToSouth");
            return (Criteria) this;
        }

        public Criteria andDistanceToSouthIn(List<String> values) {
            addCriterion("distance_to_south in", values, "distanceToSouth");
            return (Criteria) this;
        }

        public Criteria andDistanceToSouthNotIn(List<String> values) {
            addCriterion("distance_to_south not in", values, "distanceToSouth");
            return (Criteria) this;
        }

        public Criteria andDistanceToSouthBetween(String value1, String value2) {
            addCriterion("distance_to_south between", value1, value2, "distanceToSouth");
            return (Criteria) this;
        }

        public Criteria andDistanceToSouthNotBetween(String value1, String value2) {
            addCriterion("distance_to_south not between", value1, value2, "distanceToSouth");
            return (Criteria) this;
        }

        public Criteria andRatingsIsNull() {
            addCriterion("ratings is null");
            return (Criteria) this;
        }

        public Criteria andRatingsIsNotNull() {
            addCriterion("ratings is not null");
            return (Criteria) this;
        }

        public Criteria andRatingsEqualTo(Double value) {
            addCriterion("ratings =", value, "ratings");
            return (Criteria) this;
        }

        public Criteria andRatingsNotEqualTo(Double value) {
            addCriterion("ratings <>", value, "ratings");
            return (Criteria) this;
        }

        public Criteria andRatingsGreaterThan(Double value) {
            addCriterion("ratings >", value, "ratings");
            return (Criteria) this;
        }

        public Criteria andRatingsGreaterThanOrEqualTo(Double value) {
            addCriterion("ratings >=", value, "ratings");
            return (Criteria) this;
        }

        public Criteria andRatingsLessThan(Double value) {
            addCriterion("ratings <", value, "ratings");
            return (Criteria) this;
        }

        public Criteria andRatingsLessThanOrEqualTo(Double value) {
            addCriterion("ratings <=", value, "ratings");
            return (Criteria) this;
        }

        public Criteria andRatingsIn(List<Double> values) {
            addCriterion("ratings in", values, "ratings");
            return (Criteria) this;
        }

        public Criteria andRatingsNotIn(List<Double> values) {
            addCriterion("ratings not in", values, "ratings");
            return (Criteria) this;
        }

        public Criteria andRatingsBetween(Double value1, Double value2) {
            addCriterion("ratings between", value1, value2, "ratings");
            return (Criteria) this;
        }

        public Criteria andRatingsNotBetween(Double value1, Double value2) {
            addCriterion("ratings not between", value1, value2, "ratings");
            return (Criteria) this;
        }

        public Criteria andPostcodeIsNull() {
            addCriterion("postcode is null");
            return (Criteria) this;
        }

        public Criteria andPostcodeIsNotNull() {
            addCriterion("postcode is not null");
            return (Criteria) this;
        }

        public Criteria andPostcodeEqualTo(String value) {
            addCriterion("postcode =", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeNotEqualTo(String value) {
            addCriterion("postcode <>", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeGreaterThan(String value) {
            addCriterion("postcode >", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeGreaterThanOrEqualTo(String value) {
            addCriterion("postcode >=", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeLessThan(String value) {
            addCriterion("postcode <", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeLessThanOrEqualTo(String value) {
            addCriterion("postcode <=", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeLike(String value) {
            addCriterion("postcode like", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeNotLike(String value) {
            addCriterion("postcode not like", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeIn(List<String> values) {
            addCriterion("postcode in", values, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeNotIn(List<String> values) {
            addCriterion("postcode not in", values, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeBetween(String value1, String value2) {
            addCriterion("postcode between", value1, value2, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeNotBetween(String value1, String value2) {
            addCriterion("postcode not between", value1, value2, "postcode");
            return (Criteria) this;
        }

        public Criteria andDistanceToCampusIsNull() {
            addCriterion("distance_to_campus is null");
            return (Criteria) this;
        }

        public Criteria andDistanceToCampusIsNotNull() {
            addCriterion("distance_to_campus is not null");
            return (Criteria) this;
        }

        public Criteria andDistanceToCampusEqualTo(Double value) {
            addCriterion("distance_to_campus =", value, "distanceToCampus");
            return (Criteria) this;
        }

        public Criteria andDistanceToCampusNotEqualTo(Double value) {
            addCriterion("distance_to_campus <>", value, "distanceToCampus");
            return (Criteria) this;
        }

        public Criteria andDistanceToCampusGreaterThan(Double value) {
            addCriterion("distance_to_campus >", value, "distanceToCampus");
            return (Criteria) this;
        }

        public Criteria andDistanceToCampusGreaterThanOrEqualTo(Double value) {
            addCriterion("distance_to_campus >=", value, "distanceToCampus");
            return (Criteria) this;
        }

        public Criteria andDistanceToCampusLessThan(Double value) {
            addCriterion("distance_to_campus <", value, "distanceToCampus");
            return (Criteria) this;
        }

        public Criteria andDistanceToCampusLessThanOrEqualTo(Double value) {
            addCriterion("distance_to_campus <=", value, "distanceToCampus");
            return (Criteria) this;
        }

        public Criteria andDistanceToCampusIn(List<Double> values) {
            addCriterion("distance_to_campus in", values, "distanceToCampus");
            return (Criteria) this;
        }

        public Criteria andDistanceToCampusNotIn(List<Double> values) {
            addCriterion("distance_to_campus not in", values, "distanceToCampus");
            return (Criteria) this;
        }

        public Criteria andDistanceToCampusBetween(Double value1, Double value2) {
            addCriterion("distance_to_campus between", value1, value2, "distanceToCampus");
            return (Criteria) this;
        }

        public Criteria andDistanceToCampusNotBetween(Double value1, Double value2) {
            addCriterion("distance_to_campus not between", value1, value2, "distanceToCampus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusIsNull() {
            addCriterion("delete_status is null");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusIsNotNull() {
            addCriterion("delete_status is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusEqualTo(Boolean value) {
            addCriterion("delete_status =", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusNotEqualTo(Boolean value) {
            addCriterion("delete_status <>", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusGreaterThan(Boolean value) {
            addCriterion("delete_status >", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("delete_status >=", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusLessThan(Boolean value) {
            addCriterion("delete_status <", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("delete_status <=", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusIn(List<Boolean> values) {
            addCriterion("delete_status in", values, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusNotIn(List<Boolean> values) {
            addCriterion("delete_status not in", values, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("delete_status between", value1, value2, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("delete_status not between", value1, value2, "deleteStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table accommodation
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}