package liv.ac.uk.live_in.mapper;

import liv.ac.uk.live_in.dao.Accommodation;
import liv.ac.uk.live_in.dao.AccommodationExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface AccommodationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    int countByExample(AccommodationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    int deleteByExample(AccommodationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    int insert(Accommodation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    int insertSelective(Accommodation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    List<Accommodation> selectByExample(AccommodationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    Accommodation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Accommodation record, @Param("example") AccommodationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Accommodation record, @Param("example") AccommodationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Accommodation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accommodation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Accommodation record);

    List<Accommodation> customSelectByKeyword(@Param("keyword") String keyword);


}