package liv.ac.uk.live_in.mapper;

import liv.ac.uk.live_in.dao.Preference;
import liv.ac.uk.live_in.dao.PreferenceExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface PreferenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbggenerated
     */
    int countByExample(PreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbggenerated
     */
    int deleteByExample(PreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbggenerated
     */
    int insert(Preference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbggenerated
     */
    int insertSelective(Preference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbggenerated
     */
    List<Preference> selectByExampleWithBLOBs(PreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbggenerated
     */
    List<Preference> selectByExample(PreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbggenerated
     */
    Preference selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Preference record, @Param("example") PreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Preference record, @Param("example") PreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Preference record, @Param("example") PreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Preference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Preference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Preference record);
}